dynamic_collections:
  Genres:         # mapping name does not matter just needs to be unique
    type: album_genre
    title_format: <<key_name>> Albums
  Styles:         # mapping name does not matter just needs to be unique
    type: album_style
    title_format: <<key_name>> Artists
